### PR TITLE
Blocks can be instantiated with shorthand notation

### PR DESCRIPTION
**Pull request by agrevin**

### CODE REVIEW

**Comment by jjts** [comment]
Can i put one connection per line?

**Comment by agrevin** [comment]
> Can i put one connection per line?

Not yet, I'm working on it and the verification of the direction

**Comment by jjts** [comment]
No example given

**Comment by agrevin** [comment]
> Can i put one connection per line?

Yes, as of https://github.com/IObundle/py2hwsw/pull/47/commits/1f4261af6ee6291495ee389cfab41dcedf9b79ce

**Comment by jjts** [comment]
Checks need top be passing please

**Comment by jjts** [comment]
Please rewrite the iob_aoi to have all shorthand notations available

**Review by arturum1 — APPROVED** [review]

**Pull request merged**
